<a href="https://colab.research.google.com/github/akhilesh2009/Analysing-pharmaceutical-sales-data/blob/main/Analysing_pharmaceutical_sales_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [18]:
sales = pd.read_csv("salesdaily.csv")
sales

,datum,M01AB,M01AE,N02BA,N02BE,N05B,N05C,R03,R06,Year,Month,Hour,Weekday Name
0,1/2/2014,0.00,3.670,3.40,32.40,7.0,0.0,0.0,2.00,2014,1,248,Thursday
1,1/3/2014,8.00,4.000,4.40,50.60,16.0,0.0,20.0,4.00,2014,1,276,Friday
2,1/4/2014,2.00,1.000,6.50,61.85,10.0,0.0,9.0,1.00,2014,1,276,Saturday
3,1/5/2014,4.00,3.000,7.00,41.10,8.0,0.0,3.0,0.00,2014,1,276,Sunday
4,1/6/2014,5.00,1.000,4.50,21.70,16.0,2.0,6.0,2.00,2014,1,276,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2101,10/4/2019,7.34,5.683,2.25,22.45,13.0,0.0,1.0,1.00,2019,10,276,Friday
2102,10/5/2019,3.84,5.010,6.00,25.40,7.0,0.0,0.0,0.33,2019,10,276,Saturday
2103,10/6/2019,4.00,11.690,2.00,34.60,6.0,0.0,5.0,4.20,2019,10,276,Sunday
2104,10/7/2019,7.34,4.507,3.00,50.80,6.0,0.0,10.0,1.00,2019,10,276,Monday
2105,10/8/2019,0.33,1.730,0.50,44.30,20.0,2.0,2.0,0.00,2019,10,190,Tuesday

In [19]:
sales.describe()

,M01AB,M01AE,N02BA,N02BE,N05B,N05C,R03,R06,Year,Month,Hour
count,2106.000000,2106.000000,2106.000000,2106.000000,2106.000000,2106.000000,2106.000000,2106.000000,2106.000000,2106.000000,2106.000000
mean,5.033683,3.895830,3.880441,29.917095,8.853627,0.593522,5.512262,2.900198,2016.401235,6.344255,275.945869
std,2.737579,2.133337,2.384010,15.590966,5.605605,1.092988,6.428736,2.415816,1.665060,3.386954,1.970547
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2014.000000,1.000000,190.000000
25%,3.000000,2.340000,2.000000,19.000000,5.000000,0.000000,1.000000,1.000000,2015.000000,3.000000,276.000000
50%,4.990000,3.670000,3.500000,26.900000,8.000000,0.000000,4.000000,2.000000,2016.000000,6.000000,276.000000
75%,6.670000,5.138000,5.200000,38.300000,12.000000,1.000000,8.000000,4.000000,2018.000000,9.000000,276.000000
max,17.340000,14.463000,16.000000,161.000000,54.833333,9.000000,45.000000,15.000000,2019.000000,12.000000,276.000000

In [20]:
sales.head()

,datum,M01AB,M01AE,N02BA,N02BE,N05B,N05C,R03,R06,Year,Month,Hour,Weekday Name
0,1/2/2014,0.0,3.67,3.4,32.40,7.0,0.0,0.0,2.0,2014,1,248,Thursday
1,1/3/2014,8.0,4.00,4.4,50.60,16.0,0.0,20.0,4.0,2014,1,276,Friday
2,1/4/2014,2.0,1.00,6.5,61.85,10.0,0.0,9.0,1.0,2014,1,276,Saturday
3,1/5/2014,4.0,3.00,7.0,41.10,8.0,0.0,3.0,0.0,2014,1,276,Sunday
4,1/6/2014,5.0,1.00,4.5,21.70,16.0,2.0,6.0,2.0,2014,1,276,Monday

# **What are the total sales quantities for each drug category (ATC code)?**

**Total M01AB Sales**

In [21]:
total_m01ab_sales = float(sales["M01AB"].sum().round(2))
total_m01ab_sales

10600.94

**Total M01AE Sales**

In [22]:
total_m01ae_sales = float(sales["M01AE"].sum().round(2))
total_m01ae_sales

8204.62

**Total N02BA Sales**

In [23]:
total_n02ba_sales = float(sales["N02BA"].sum().round(2))
total_n02ba_sales

8172.21

**Total N02BE Sales**

In [24]:
total_n02be_sales = float(sales["N02BE"].sum().round(2))
total_n02be_sales

63005.4

**Total N05B Sales**

In [25]:
total_n05b_sales = float(sales["N05B"].sum().round(2))
total_n05b_sales

18645.74

**Total N05C Sales**

In [26]:
total_n05c_sales = float(sales["N05C"].sum().round(2))
total_n05c_sales

1249.96

**Total R03 Sales**

In [27]:
total_ro3_sales = float(sales["R03"].sum().round(2))
total_ro3_sales

11608.82

**Total R06 Sales**

In [28]:
total_r06_sales = float(sales["R06"].sum().round(2))
total_r06_sales

6107.82

# **Which individual drug brands have the highest total sales?**

**Putting total sales of each drug in a dictionary**

In [29]:
total_sales = {
          "M01AB": total_m01ab_sales,
          "M01AE": total_m01ae_sales,
          "N02BA": total_n02ba_sales,
          "N02BE": total_n02be_sales,
          "N05B": total_n05b_sales,
          "N05C": total_n05c_sales,
          "R03":total_ro3_sales,
          "R06": total_r06_sales
          }

drug_with_highest_sales = max(total_sales, key=total_sales.get)
highest_sales_value = total_sales[drug_with_highest_sales]

**Highest Sale**

In [30]:
print(f"Drug {drug_with_highest_sales} has the highest sales of {highest_sales_value}")

Drug N02BE has the highest sales of 63005.4

# **Which three drugs have the highest sales in January 2015, July 2016, September 2017.**

# ***Which three drugs have the highest sales in January 2015.***

**M01AB total sales Jan 2015**

In [68]:
m01ab_jan_2015 = float(sales[((sales["Year"] == 2015) & (sales["Month"] == 1))]["M01AB"].sum().round(2))
m01ab_jan_2015

135.91

**M01AE total sales Jan 2015**

In [67]:
m01ae_jan_2015 = float(sales[((sales["Year"] == 2015) & (sales["Month"] == 1))]["M01AE"].sum().round(2))
m01ae_jan_2015

130.35

**N02BA total sales Jan 2015**

In [66]:
n02ba_jan_sales = float(sales[((sales["Year"] == 2015) & (sales["Month"] == 1))]["N02BA"].sum().round(2))
n02ba_jan_sales

141.0

**N02BE total sales Jan 2015**

In [69]:
n02be_jan_sales = float(sales[((sales["Year"] == 2015) & (sales["Month"] == 1))]["N02BE"].sum().round(2))
n02be_jan_sales

1044.24

**N05B total sales Jan 2015**

In [70]:
n05b_jan_sales = float(sales[((sales["Year"] == 2015) & (sales["Month"] == 1))]["N05B"].sum().round(2))
n05b_jan_sales

463.0

**N05C total sales Jan 2015**

In [71]:
n05c_jan_sales = float(sales[((sales["Year"] == 2015) & (sales["Month"] == 1))]["N05C"].sum().round(2))
n05c_jan_sales

24.0

**R03 total sales Jan 2015**

In [72]:
r03_jan_sales = float(sales[((sales["Year"] == 2015) & (sales["Month"] == 1))]["R03"].sum().round(2))
r03_jan_sales

177.25

**R06 total sales Jan 2015**

In [73]:
r06_jan_sales = float(sales[((sales["Year"] == 2015) & (sales["Month"] == 1))]["R06"].sum().round(2))
r06_jan_sales

42.0

**Putting then all in a array and using np.sort()**

In [ ]:
sales_2015_arr = np.array([m01ab_jan_2015, m01ab_jan_2015, n02ba_jan_sales, n02be_jan_sales, n05b_jan_sales, n05c_jan_sales, r03_jan_sales, r06_jan_sales])